CREATE DATABASE IF NOT EXISTS appdb;

CREATE USER IF NOT EXISTS 'haproxy'@'%' IDENTIFIED BY '';
FLUSH PRIVILEGES;

-- CREATE USER IF NOT EXISTS 'RoyBatty'@'%' IDENTIFIED BY 'RoyBatty2019';
-- GRANT ALL PRIVILEGES ON appdb.* TO 'RoyBatty'@'%' WITH GRANT OPTION;
-- FLUSH PRIVILEGES;

USE appdb;
CREATE TABLE IF NOT EXISTS `test` (
    `id` INT(11) NOT NULL,
    `name` VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
) ENGINE=innodb ;
